### ISSUE TITLE
Get API onboard umbrella issue

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes-sigs/work-api#2]
After discussed with @qiujian16, we decide to file this issue to track tasks of getting [Work] API get onboard.

- API
  - [x] Public review API(more focus on each fields and conditions).
  - [x] scripts for deepcopy-gen/informer-gen/client-gen/lister-gen/register-gen.
- Reference implementation(controllers)
  - [x] controller implementation
  - [x] webhook implementation
  - [x] Unit tests
  - [x] E2E tests
- Docs
  - [x] Design docs
  - [x] Other docs if there is any
- CI
  - [x] verify scripts and tests
- ~~Define Graduation Criteria~~ (talk about this later)
  - [ ] Alpha -> Beta Graduation
  - [ ] Beta -> GA Graduation

**Comment by RainbowMango** [comment]
/close
The API has been merged in. Closing this issue now.
